--1. Total appointments per doctor
SELECT d.doctor_id, COUNT(a.appointment_id) AS number_of_appointments FROM doctors d
FULL JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id
ORDER BY number_of_appointments DESC;

--2. List patients along with their doctor names for each appointment
SELECT p.patient_id, d.doctor_id, appointment_date FROM appointments a 
JOIN doctors d ON a.doctor_id = d.doctor_id
JOIN patients p  ON a.patient_id = p.patient_id;

--3. Find total revenue generated by each treatment type
SELECT treatment_type, ROUND(SUM(cost)::numeric,2) AS Revenue FROM treatments t
JOIN billing b ON t.treatment_id = b.treatment_id
WHERE payment_status = 'Paid'
GROUP BY treatment_type;

--4. Count number of appointments by status (Completed, Cancelled, No-show)
SELECT status, COUNT(*) FROM appointments
GROUP BY status;

--5. Find average treatment cost by doctor specialization
SELECT d.specialization, ROUND(AVG(cost)::numeric,2) FROM doctors d
JOIN appointments a ON d.doctor_id = a.doctor_id
JOIN treatments t ON a.appointment_id = t.appointment_id
GROUP BY d.specialization;

--6. Find doctors who handled more than 20 appointments
SELECT d.doctor_id, COUNT(*) FROM doctors d 
JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id
HAVING COUNT(*) > 20;

--7. Find patients who have visited more than once (repeat patients)
SELECT p.patient_id, COUNT(p.patient_id) FROM patients p 
JOIN appointments a ON p.patient_id = a.patient_id
GROUP BY p.patient_id
HAVING COUNT(p.patient_id) > 1;

--8. Revenue by Insurance Providers
SELECT insurance_provider, ROUND(SUM(amount)::numeric,2) FROM billing b 
JOIN treatments t ON b.treatment_id = t.treatment_id
JOIN patients p ON b.patient_id = p.patient_id
WHERE payment_method = 'Insurance'
GROUP BY insurance_provider;

--9. Find doctors whose average treatment cost is above overall average
SELECT d.doctor_id, ROUND(AVG(t.cost)::numeric, 2) AS avg_doctor_cost FROM doctors d
JOIN appointments a ON d.doctor_id = a.doctor_id
JOIN treatments t ON a.appointment_id = t.appointment_id
GROUP BY d.doctor_id
HAVING AVG(t.cost) > (SELECT AVG(t2.cost) FROM doctors d2
    				  JOIN appointments a2 ON d2.doctor_id = a2.doctor_id
      				  JOIN treatments t2 ON a2.appointment_id = t2.appointment_id);

--10. Ranking Doctors based on Number of Appointments they handled
SELECT d.doctor_id, COUNT(*), RANK() OVER ( ORDER BY COUNT(*) DESC) FROM doctors d 
JOIN appointments a ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id;

--11. Find top 2 patients (per doctor) with most visits
SELECT * FROM (SELECT p.patient_id, d.doctor_id, COUNT(p.patient_id), ROW_NUMBER() OVER (PARTITION BY d.doctor_id ORDER BY COUNT(p.patient_id) DESC) AS rn FROM patients p
JOIN appointments a ON p.patient_id = a.patient_id
JOIN doctors d ON d.doctor_id = a.doctor_id
GROUP BY d.doctor_id, p.patient_id)
WHERE rn <=2;

--12. Identify patients with highest total billing amount using CTE
WITH total_revenue AS 
(SELECT p.patient_id, SUM(amount) as totaL_bill FROM patients p 
JOIN billing b ON p.patient_id = b.patient_id
GROUP BY p.patient_id
ORDER BY totaL_bill DESC)

SELECT patient_id, ROUND(total_bill::numeric,2) AS total_amount, RANK() OVER (ORDER BY total_bill DESC) FROM total_revenue;